### PR TITLE
Fix method syntax in ReadMe example code 

### PR DESCRIPTION
**Pull request by GAM3RG33K**
The method was declared with an expression body but it ended with a `}`. So I fixed this by replacing the expression body symbol with a '{'.

### CODE REVIEW

**Comment by GAM3RG33K** [comment]
This is my first contribution here, so please guide me if you find any issues in this pull request or format of the description.

**Comment by GAM3RG33K** [comment]
@googlebot I signed it!

**Comment by GAM3RG33K** [comment]
@kevmoo Hi, I don't know if I need to wait for any reviewer or somebody, but I just wanted to draw attention to this pull request. It's not a big change in code. So, please let me know what to do next. This is my first time contributing here.

**Review by lrhn — APPROVED** [review]
Good catch, that should indeed be a `{`.
Thank you for the PR, it looks perfectly fine.

**Pull request merged**
